version: "3.8"

services:
  app:
    image: phamtanminhtien/fake-smtp-server:latest
    container_name: fake-smtp-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "2525:2525"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
