version: "3.8"

services:
  backend:
    build:
      target: development
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      target: development
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
    ports:
      - "5173:5173"
